### ISSUE TITLE
subPackages无效

### ISSUE THREAD

**Issue by QiYan925** [uni-helper/vite-plugin-uni-layouts#11]
### 描述问题

在 pages.json 中的subPackages配置layout无效

### 复现

  "subPackages": [
    {
      "root": "pages-sub",
      "pages": [
        {
          "path": "test/test",
          "type": "page",
          "layout": "default"
        }
      ]
    }
  ]

### 系统信息

```Shell
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 394.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
  Browsers:
    Safari: 16.4
```

### 使用的包管理器

npm

### 核对

- [x] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [x] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
try 0.1.1
