### ISSUE TITLE
在Layout中设置page节点下的属性不会生效

### ISSUE THREAD

**Issue by censujiang** [uni-helper/vite-plugin-uni-layouts#21]
### 描述问题

在任意layout组件中的css标签（非scoped）设置任何有关page节点的属性都会失败

### 复现

在任意layout组件中添加以下代码：

```css
page {
  background-color: blue;
}
```

观察发现页面不会变蓝

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 40.64 GB / 63.95 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (117.0.2045.36)    
    Internet Explorer: 11.0.19041.3636
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
布局组件不是魔法，它是组件，组件能修改它就能修改，组件不能它也不能。

**Comment by censujiang** [comment]
可以尝试提升作用域？
