### ISSUE TITLE
hbuilder中的layouts

### ISSUE THREAD

**Issue by haodan123** [uni-helper/vite-plugin-uni-layouts#22]
### 对问题的清晰和简明的描述

请问在hbuilder中创建的项目可以使用这个uni-layouts吗

### 推荐的解决方案

请问在hbuilder中创建的项目可以使用这个uni-layouts吗

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
暂无计划
