### ISSUE TITLE
使用这个 layouts 后，是不是新增的vue文件都必须重新运行一下才行

### ISSUE THREAD

**Issue by lyumg** [uni-helper/vite-plugin-uni-layouts#23]
### 描述问题

使用 layouts 和 uni-pages后，新增一个 vue 文件，跳转到新 vue 页面后没有 layouts，重新运行编译一下才显示

### 复现

无

### 系统信息

```Shell
无
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
理论上不需要，如果需要那就是bug

**Comment by lyumg** [comment]
> 理论上不需要，如果需要那就是bug

那么目前可能就是bug了，我下载 `Vitesse for uni-app` 后，运行起来以后添加的vue文件没有 `layouts` ，必须要重新运行才可以

**Comment by KeJunMao** [comment]
嗯呢，已经复现了，H5 没这个问题
