### ISSUE TITLE
使用name去切换布局失败，是要先注册好layout里面要用的组件吗

### ISSUE THREAD

**Issue by catdddmouse** [uni-helper/vite-plugin-uni-layouts#30]
### Describe the bug

直接用name的话是可以的，但是name改成响应式就不行了

![image](https://github.com/uni-helper/vite-plugin-uni-layouts/assets/130121308/90ec89a1-db4c-4df1-964e-00bfbe361897)
![image](https://github.com/uni-helper/vite-plugin-uni-layouts/assets/130121308/69146ef0-f676-4607-9cc5-8764eb84ee8f)

### Reproduction

<uni-layout :name="supervisorLayout">
const supervisorLayout = ref('default')

![image](https://github.com/uni-helper/vite-plugin-uni-layouts/assets/130121308/61d40f50-fe95-4240-87cd-b2b5ad6ed76e)

### System Info

 "@uni-helper/vite-plugin-uni-layouts": "^0.1.7",

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by skiyee** [comment]
需要在使用自定义布局页面禁用布局

使用说明：[动态布局和额外插槽](https://github.com/uni-helper/vite-plugin-uni-layouts?tab=readme-ov-file#%E5%8A%A8%E6%80%81%E5%B8%83%E5%B1%80%E5%92%8C%E9%A2%9D%E5%A4%96%E6%8F%92%E6%A7%BD)

无使用 `vite-plugin-uni-pages` 禁用方法：[pages.json下禁用](https://github.com/uni-helper/vite-plugin-uni-layouts?tab=readme-ov-file#%E7%A6%81%E7%94%A8%E5%B8%83%E5%B1%80)

使用 `vite-plugin-uni-pages` 禁用方法：[route-block](https://github.com/uni-helper/vite-plugin-uni-layouts?tab=readme-ov-file#%E6%B3%A8%E6%84%8F)
