### ISSUE TITLE
更新uniapp最新后布局失效。

### ISSUE THREAD

**Issue by gao-xiang** [uni-helper/vite-plugin-uni-layouts#36]
### 描述问题

npx @dcloudio/uvm@latest
 执行后，所有页面使用的布局失效。

### 复现

npx @dcloudio/uvm@latest
 执行后，所有页面使用的布局失效。

### 系统信息

基础环境信息:
  - os: `Windows 11 10.0.22631`
  - node: `18.16.1`
  - vscode: `1.89.1`
  - volar: `2.0.19`

基础依赖信息:
  - vue: `3.4.27`
  - vite: `5.2.8`
  - @dcloudio/uni-app: `3.0.0-alpha-4010720240511003`

uni-helper依赖信息:
  - @uni-helper/vite-plugin-uni-layouts: `0.1.8`

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
请提供完整复现

**Comment by gao-xiang** [comment]
使用多个包，升级后出现错误，

`npx degit ares-chang/uni-vitesse my-uni-app`  下载框架包，
pnpm i
`npx @dcloudio/uvm@latest
` 升级到最新版本
pnpm dev:h5


更换多个模块，或使用uniapp 官方 ts 包升级也一样的报错，
https://github.com/codercup/unibest

**Comment by LetFree** [comment]
+1
```
<route lang="json5">
{
  layout: "default",
}
</route>
```
默认布局，配置与否都不生效了

**Comment by skiyee** [comment]
已复现问题，正在修复

**Comment by skiyee** [comment]
已修复，等待Review中

若着急使用的朋友，把 `@uni-helper/vite-plugin-uni-layouts` 依赖降至 `v0.1.7`
