### ISSUE TITLE
在自己本机试了一下，好像不支持多重layout嵌套

### ISSUE THREAD

**Issue by AarNtyon** [uni-helper/vite-plugin-uni-layouts#47]
### 描述问题

比如tabbar，几个页面共用一个tabbar layout，而这个tabbar layout 可以被root layout 包裹。

### 复现

如上所述

### 系统信息

1

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by ModyQyW** [comment]
请提供复现

**Comment by AarNtyon** [comment]
类似这样,目前只会渲染第一层
` <uni-layout name="default">
    <uni-layout name="tabbar">
      <view>content</view>
    </uni-layout>
  </uni-layout>
`

**Comment by AarNtyon** [comment]
> 类似这样,目前只会渲染第一层 `<uni-layout name="default"> <uni-layout name="tabbar"> <view>content</view> </uni-layout> </uni-layout>`

![Uploading image.png…]()

**Comment by xingchenwl** [comment]
这个问题25年了 依旧存在不知道是不是我使用有问题
